<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_failure_output" errors="1" failures="20" tests="21" time="0.12117" hostname="unknown" timestamp="2015-01-07T21:36:09">
  <properties/>
  <testcase classname="test_failure_output" name="test_empty">
    <failure>
(No failure message provided)
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 13.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_not_empty">
    <failure>
(No failure message provided)
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 18.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_false">
    <failure>
(No failure message provided)
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 23.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_true">
    <failure>
(No failure message provided)
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 28.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_fail">
    <failure>
This some custom fail message
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 32.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_equals">
    <failure>
Data not equal:
  Expected : 3
  Actual   : 4
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 37.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_equals_array">
    <failure>
Data not equal:
  Expected : [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16]
  Actual   : [1 2 3 4 5 6 7 8 9 10.000001 11 12 13 14 15]
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 43.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_equals_arraymatrix">
    <failure>
Data not equal:
  Expected : [1 2 3 4;5 6 7 8;9 10 11 12;13 14 15 16]
  Actual   : [1 2 3 4;5 6 7 8;9 10.000001 11 12;13 14 15 16]
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 51.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_equals_string">
    <failure>
Data not equal:
  Expected : 'foo'
  Actual   : 'fOo'
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 56.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_equals_cell">
    <failure>
Data not equal:
  Expected : {3, 'foo'}
  Actual   : {3, 'fOo'}
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 63.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_equals_struct">
    <failure>
Data not equal:
  Expected : [{foo:{'hi', 'ho'}; bar:[3 4]}]
  Actual   : [{foo:{'ho', 'hi'}; bar:[3 4]}]
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 71.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_equals_nested_struct">
    <failure>
Data not equal:
  Expected : [{foo:{'hi', 'ho'}; bar:[3 4]; tee:[{foo:{'hi', 'ho'}; bar:[3 4]}]}]
  Actual   : [{foo:{'hi', 'ho'}; bar:[3 4]; tee:[{foo:{'ho', 'hi'}; bar:[3 4]}]}]
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 80.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_equals_nested_struct_multiple_differences">
    <failure>
Data not equal:
  Expected : [{foo:{'hi', 'ho'}; bar:[3 4]; tee:[{foo:{'hi', 'ho'}; bar:[3 4]}]}]
  Actual   : [{foo:{'hi', 'ho'}; bar:[3 4]; tee:[{foo:{'ho', 'hi'}; bar:[3 5]}]}]
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 90.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_equals_structarray">
    <failure>
Data not equal:
  Expected : [{foo:{'hi', 'ho'}; bar:3}, {foo:{'hi', 'ho'}; bar:4}]
  Actual   : [{foo:{'hi', 'ho'}; bar:3}, {foo:{'ho', 'hi'}; bar:4}]
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 98.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_not_equals">
    <failure>
Expected and actual are equal.
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 103.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_error">
    <failure>
Error expected, but none occurred.
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 108.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_typed_error">
    <failure>
Error expected, but none occurred.
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 113.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_wrong_typed_error">
    <failure>
Error occurred, but did not match criteria. Expected error identifier 'MATLAB:SomeError' actually was 'MATLAB:m_improper_grouping'.
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 117.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_warning">
    <failure>
No warning MATLAB:rmpath:DirNotFound when executing function @()3.
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 123.
    </failure>
  </testcase>
  <testcase classname="test_failure_output" name="test_implementation_fault">
    <error>
Undefined function or variable 'unknown_function_call'.
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 127
In C:\Users\Alexander\repositories\mlunit\src\@function_test_case\run_test.m at line 21
In C:\Users\Alexander\repositories\mlunit\src\@test_case\run.m at line 42
In C:\Users\Alexander\repositories\mlunit\src\@test_suite\run.m at line 24
In C:\Users\Alexander\repositories\mlunit\src\automation\recursive_test_run.m at line 84
In C:\Users\Alexander\repositories\mlunit\src\automation\recursive_test_run.m at line 41
    </error>
  </testcase>
  <testcase classname="test_failure_output" name="test_nested_functions">
    <failure>
Nested function test.
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 135.
In C:\Users\Alexander\repositories\mlunit\sample\failure_samples\test_failure_output.m at line 131.
    </failure>
  </testcase>
  <system-out/>
  <system-err/>
</testsuite>
